[colors.primary]
background = '#0f0f0e'
foreground = '#fafafa' 

[colors.normal]
black   = '#050702'
red     = '#564C53'
green   = '#4F5D5A'
yellow  = '#777365'
blue    = '#728376'
magenta = '#8C8F7B'
cyan    = '#9AA583'
white   = '#C6CCB7'

[colors.bright]
black   = '#828775'
red     = '#564C53'
green   = '#4F5D5A'
yellow  = '#777365'
blue    = '#728376'
magenta = '#8C8F7B'
cyan    = '#9AA583'
white   = '#DADDD3'

