#!/bin/bash
myself=$(basename "$0")
for pid in $(pidof -x "$myself"); do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi
done

TARGET=$1
WIDGETS="menu slider_vol slider_bri system_dashboard power_menu"

eww close $WIDGETS
PID=$!
wait $PID

if [ $TARGET == "none" ]; then
	hyprctl dispatch 'hl.dsp.submap("reset")'
	eww close close_overlay
else
	eww open close_overlay && eww open $TARGET
	hyprctl dispatch 'hl.dsp.submap("eww")'
fi
	
