#!/bin/bash
TARGET=$1
WIDGETS="slider_vol slider_bri system_dashboard menu"
for widget in $WIDGETS; do
	eww close $widget
done

sleep 0.1
if [ $TARGET == "none" ]; then
	hyprctl dispatch 'hl.dsp.submap("reset")'
	eww close close_overlay
else
	eww open close_overlay && eww open $TARGET
	hyprctl dispatch 'hl.dsp.submap("eww")'
fi
	
