[colors.primary]
background = '#0f0f0e'
foreground = '#fafafa' 

[colors.normal]
black   = '#01070A'
red     = '#49556C'
green   = '#4D5971'
yellow  = '#546477'
blue    = '#5C7C8F'
magenta = '#AAD4E4'
cyan    = '#A4D5E9'
white   = '#C8EDFD'

[colors.bright]
black   = '#799BA9'
red     = '#49556C'
green   = '#4D5971'
yellow  = '#546477'
blue    = '#5C7C8F'
magenta = '#AAD4E4'
cyan    = '#A4D5E9'
white   = '#DBEEF5'

