#!/bin/bash

install-dependencies() {
	deps_file="$1/setup/dots.deps"
	echo $deps_file

	for pkg in $(cat $deps_file); do
	    if ! pacman -Q "$pkg" &>/dev/null; then
		echo "Installing: $pkg"
		yay -S --needed --noconfirm "$pkg"
	    else
		echo "Already installed: $pkg"
	    fi
	done
}
