#!/bin/bash

install-dependencies() {
	deps_file="$1/dots.deps"

	for pkg in $(ls $deps); do
	    if ! pacman -Q "$pkg" &>/dev/null; then
		echo "Installing: $pkg"
		yay -S --needed --noconfirm "$pkg"
	    else
		echo "Already installed: $pkg"
	    fi
	done
}
